### ISSUE TITLE
No module named 'playlists', running nose2 test for exaile.

### ISSUE THREAD

**Issue by jeffreybarron** [egh/spydaap#15]
trying to create tests for exaile (a UNI Assessment) but I get this error when running nose2

Traceback (most recent call last):
  File "/home/exaile/.local/bin/spydaap", line 5, in <module>
    from spydaap.cli import main
  File "/home/exaile/.local/lib/python3.8/site-packages/spydaap/__init__.py", line 17, in <module>
    import playlists
ModuleNotFoundError: No module named 'playlists'

however the playlists.py module is in /home/exaile/.local/lib/python3.8/site-packages/spydaap/
please help

**Comment by egh** [comment]
Should perhaps be fixed in https://github.com/egh/spydaap/commit/2f14b2385af2b361bc40906cb5cf30d245cdebc8

**Comment by mrkapqa** [comment]
having simiilar issue here

`ERROR   : Unable to enable plugin daapclient
Traceback (most recent call last):
  File "/usr/lib/exaile/xl/plugins.py", line 162, in enable_plugin
    plugin = self.load_plugin(pluginname)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/exaile/xl/plugins.py", line 88, in load_plugin
    spec.loader.exec_module(plugin)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/share/exaile/plugins/daapclient/__init__.py", line 35, in <module>
    from .client import DAAPClient
  File "/usr/share/exaile/plugins/daapclient/client.py", line 5, in <module>
    from spydaap.daap import DAAPError, DAAPObject, DAAPParseCodeTypes
  File "/home/rich/.local/lib/python3.12/site-packages/spydaap/__init__.py", line 17, in <module>
    import playlists
ModuleNotFoundError: No module named 'playlists'

`

install  been made via "pip"

**Comment by egh** [comment]
I'm not actively maintaining this project, but happy to merge PRs. Sorry I can't be more helpful.
